// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 07 Jan 2016 19:56:58 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include <vpx/vp8cx.h>
#include <vpx/vp8dx.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// vpx_codec_enc_output_cx_pkt_cb_fn_t_f619e593 is a proxy for callback vpx_codec_enc_output_cx_pkt_cb_fn_t.
void vpx_codec_enc_output_cx_pkt_cb_fn_t_f619e593(vpx_codec_cx_pkt_t* pkt, void* user_data);

// vpx_decrypt_cb_a470ba69 is a proxy for callback vpx_decrypt_cb.
void vpx_decrypt_cb_a470ba69(void* decrypt_state, unsigned char* input, unsigned char* output, int count);

