// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 07 Jan 2016 19:56:58 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void vpx_codec_enc_output_cx_pkt_cb_fn_t_f619e593(vpx_codec_cx_pkt_t* pkt, void* user_data) {
	codecEncOutputCxPktCbFnF619E593(pkt, user_data);
}

void vpx_decrypt_cb_a470ba69(void* decrypt_state, unsigned char* input, unsigned char* output, int count) {
	decryptCbA470BA69(decrypt_state, input, output, count);
}

