// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 06 Jan 2016 08:36:22 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include <vpx/vp8.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

