// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 07 Jan 2016 21:04:53 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void vpx_codec_enc_output_cx_pkt_cb_fn_t_f619e593(vpx_codec_cx_pkt_t* pkt, void* user_data) {
	codecEncOutputCxPktCbFnF619E593(pkt, user_data);
}

void vpx_codec_put_frame_cb_fn_t_45458e52(void* user_priv, vpx_image_t* img) {
	codecPutFrameCbFn45458E52(user_priv, img);
}

void vpx_codec_put_slice_cb_fn_t_449a5268(void* user_priv, vpx_image_t* img, vpx_image_rect_t* valid, vpx_image_rect_t* update) {
	codecPutSliceCbFn449A5268(user_priv, img, valid, update);
}

int vpx_get_frame_buffer_cb_fn_t_c9f1c700(void* priv, unsigned long int min_size, vpx_codec_frame_buffer_t* fb) {
	return getFrameBufferCbFnC9F1C700(priv, min_size, fb);
}

int vpx_release_frame_buffer_cb_fn_t_868bb8fc(void* priv, vpx_codec_frame_buffer_t* fb) {
	return releaseFrameBufferCbFn868BB8FC(priv, fb);
}

