// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 07 Jan 2016 21:04:53 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package vpx provides Go bindings for libvpx-1.5.0, the WebM Project VPx codec implementation.
*/
package vpx
