// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 25 Sep 2016 14:31:21 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package vpx provides Go bindings for libvpx-1.6.0, the WebM Project VPx codec implementation.
*/
package vpx
