// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 06 Jan 2016 08:14:46 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package vpx

/*
#cgo pkg-config: vpx
#include <vpx/vp8.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Vp8PostprocCfg as declared in vpx/vp8.h:89
type Vp8PostprocCfg struct {
	PostProcFlag    int
	DeblockingLevel int
	NoiseLevel      int
	refc33fa674     *C.vp8_postproc_cfg_t
	allocsc33fa674  interface{}
}

// RefFrame as declared in vpx/vp8.h:108
type RefFrame struct {
	FrameType      RefFrameType
	Img            Image
	ref6238b069    *C.vpx_ref_frame_t
	allocs6238b069 interface{}
}

// Vp9RefFrame as declared in vpx/vp8.h:117
type Vp9RefFrame struct {
	Idx           int
	Img           Image
	ref223f847    *C.vp9_ref_frame_t
	allocs223f847 interface{}
}

// CodecCaps type as declared in vpx/vpx_codec.h:153
type CodecCaps int

// CodecFlags type as declared in vpx/vpx_codec.h:165
type CodecFlags int

// CodecIface as declared in vpx/vpx_codec.h:173
type CodecIface C.vpx_codec_iface_t

// CodecPriv as declared in vpx/vpx_codec.h:181
type CodecPriv C.vpx_codec_priv_t

// CodecIter type as declared in vpx/vpx_codec.h:188
type CodecIter unsafe.Pointer

// CodecCtx as declared in vpx/vpx_codec.h:213
type CodecCtx struct {
	Name           string
	Iface          []CodecIface
	Err            CodecErr
	ErrDetail      string
	InitFlags      CodecFlags
	Config         [8]byte
	Priv           []CodecPriv
	ref8abc1e81    *C.vpx_codec_ctx_t
	allocs8abc1e81 interface{}
}

// Image as declared in vpx/vpx_image.h:122
type Image struct {
	Fmt            ImageFormat
	Cs             ColorSpace
	W              uint
	H              uint
	BitDepth       uint
	DW             uint
	DH             uint
	XChromaShift   uint
	YChromaShift   uint
	Planes         [4][]byte
	Stride         [4]int
	Bps            int
	UserPriv       unsafe.Pointer
	ImgData        []byte
	ImgDataOwner   int
	SelfAllocd     int
	FbPriv         unsafe.Pointer
	refc09455e3    *C.vpx_image_t
	allocsc09455e3 interface{}
}

// ImageRect as declared in vpx/vpx_image.h:130
type ImageRect struct {
	X              uint
	Y              uint
	W              uint
	H              uint
	reff3ce051f    *C.vpx_image_rect_t
	allocsf3ce051f interface{}
}
